<?php if (!defined('ENLIGHTER_INIT')) die('DIRECT ACCESS PROHIBITED'); ?>

<div class="headline">
    <h3 class="headline-title">EnlighterJS Project moved to <a href="https://codeberg.org/EnlighterJS">Codeberg.org</a></h3>

    <p class="introduction">
        After 13 years on GitHub, we have decided to migrate our repositories to Codeberg.org. 
    </p>    
    <p>This move reflects our growing concern about Microsoft`s increasing commercialization of the platform and its broader use of free and open-source software to support proprietary AI training. We believe that open-source contributions should not be treated as a resource to be extracted for closed commercial systems without clear consent and reciprocity. 
        By moving to <a href="https://docs.codeberg.org/getting-started/what-is-codeberg/#what-is-codeberg-e.v.%3F">Codeberg.org</a> - a German, non-profit community-led organization - we are choosing a platform that is more closely aligned with our values of transparency, digital sovereignty, and community-driven free software which is also made in Europe.
    </p>

    <div class="news-image">
        <img
            src="<?php echo \Enlighter\skltn\ResourceManager::getResourceUrl('about/codeberg.jpg'); ?>"
            alt="EnlighterJS Project on Codeberg">
    </div>
    <br>
    <em>
        "Codeberg is a democratic community-driven, non-profit software development platform operated by Codeberg e.V. and centered around Codeberg.org, a Forgejo-based software forge."
    </em>
</div>

<hr />

<div class="column-layout-2">

    <div class="col-md-2">
        <div class="news-section">
            <h4>Copy to clipboard</h4>

            <div class="news-image">
                <img
                    src="<?php echo \Enlighter\skltn\ResourceManager::getResourceUrl('about/copy-to-clipboard.gif'); ?>"
                    alt="Copy to clipboard tooltip">
            </div>

            <p> CSS based tooltips with visual feedback.</p>

        </div>

    </div>

    <div class="col-md-2">
        <div class="news-section">
            <h4>Dynamic-Resource-Invocation Re-Implemented</h4>

            <div class="news-image">
                <img
                    src="<?php echo \Enlighter\skltn\ResourceManager::getResourceUrl('about/bootstrap4.png'); ?>"
                    alt="bootstrap4">
            </div>

            <p>DRI compatibility for bbpress and dynamic content (jquery load, jetpack infinity scroll). <br />
            <strong>Javascript based dynamic-resource-invocation to load the EnlighterJS assets dynamically when needed (client side)</strong></p>

        </div>

    </div>

    <div class="clear"></div>

</div>
